<?php

namespace Unusualify\Modularity\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;
use Modules\SystemUtility\Entities\Country;

class DefaultCountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();

        Country::truncate();
        $countries = [
            ['id' => 1, 'code' => 'AF', 'en' => ['name' => 'Afghanistan'], 'tr' => ['name' => 'Afganistan'], 'phone_code' => 93],
            ['id' => 2, 'code' => 'AL', 'en' => ['name' => 'Albania'], 'tr' => ['name' => 'Arnavutluk'], 'phone_code' => 355],
            ['id' => 3, 'code' => 'DZ', 'en' => ['name' => 'Algeria'], 'tr' => ['name' => 'Cezayir'], 'phone_code' => 213],
            ['id' => 4, 'code' => 'AS', 'en' => ['name' => 'American Samoa'], 'tr' => ['name' => 'Amerika Samoa'], 'phone_code' => 1684],
            ['id' => 5, 'code' => 'AD', 'en' => ['name' => 'Andorra'], 'tr' => ['name' => 'Andorra'], 'phone_code' => 376],
            ['id' => 6, 'code' => 'AO', 'en' => ['name' => 'Angola'], 'tr' => ['name' => 'Angola'], 'phone_code' => 244],
            ['id' => 7, 'code' => 'AI', 'en' => ['name' => 'Anguilla'], 'tr' => ['name' => 'Anguilla'], 'phone_code' => 1264],
            ['id' => 8, 'code' => 'AQ', 'en' => ['name' => 'Antarctica'], 'tr' => ['name' => 'Antarktika'], 'phone_code' => 0],
            ['id' => 9, 'code' => 'AG', 'en' => ['name' => 'Antigua And Barbuda'], 'tr' => ['name' => 'Antigua ve Barbuda'], 'phone_code' => 1268],
            ['id' => 10, 'code' => 'AR', 'en' => ['name' => 'Argentina'], 'tr' => ['name' => 'Arjantin'], 'phone_code' => 54],
            ['id' => 11, 'code' => 'AM', 'en' => ['name' => 'Armenia'], 'tr' => ['name' => 'Ermenistan'], 'phone_code' => 374],
            ['id' => 12, 'code' => 'AW', 'en' => ['name' => 'Aruba'], 'tr' => ['name' => 'Aruba'], 'phone_code' => 297],
            ['id' => 13, 'code' => 'AU', 'en' => ['name' => 'Australia'], 'tr' => ['name' => 'Avustralya'], 'phone_code' => 61],
            ['id' => 14, 'code' => 'AT', 'en' => ['name' => 'Austria'], 'tr' => ['name' => 'Avusturya'], 'phone_code' => 43],
            ['id' => 15, 'code' => 'AZ', 'en' => ['name' => 'Azerbaijan'], 'tr' => ['name' => 'Azerbaycan'], 'phone_code' => 994],
            ['id' => 16, 'code' => 'BS', 'en' => ['name' => 'Bahamas The'], 'tr' => ['name' => 'Bahamalar'], 'phone_code' => 1242],
            ['id' => 17, 'code' => 'BH', 'en' => ['name' => 'Bahrain'], 'tr' => ['name' => 'Bahreyn'], 'phone_code' => 973],
            ['id' => 18, 'code' => 'BD', 'en' => ['name' => 'Bangladesh'], 'tr' => ['name' => 'Bangladeş'], 'phone_code' => 880],
            ['id' => 19, 'code' => 'BB', 'en' => ['name' => 'Barbados'], 'tr' => ['name' => 'Barbados'], 'phone_code' => 1246],
            ['id' => 20, 'code' => 'BY', 'en' => ['name' => 'Belarus'], 'tr' => ['name' => 'Belarus'], 'phone_code' => 375],
            ['id' => 21, 'code' => 'BE', 'en' => ['name' => 'Belgium'], 'tr' => ['name' => 'Belçika'], 'phone_code' => 32],
            ['id' => 22, 'code' => 'BZ', 'en' => ['name' => 'Belize'], 'tr' => ['name' => 'Belize'], 'phone_code' => 501],
            ['id' => 23, 'code' => 'BJ', 'en' => ['name' => 'Benin'], 'tr' => ['name' => 'Benin'], 'phone_code' => 229],
            ['id' => 24, 'code' => 'BM', 'en' => ['name' => 'Bermuda'], 'tr' => ['name' => 'Bermuda'], 'phone_code' => 1441],
            ['id' => 25, 'code' => 'BT', 'en' => ['name' => 'Bhutan'], 'tr' => ['name' => 'Bhutan'], 'phone_code' => 975],
            ['id' => 26, 'code' => 'BO', 'en' => ['name' => 'Bolivia'], 'tr' => ['name' => 'Bolivia'], 'phone_code' => 591],
            ['id' => 27, 'code' => 'BA', 'en' => ['name' => 'Bosnia and Herzegovina'], 'tr' => ['name' => 'Bosna ve Hersek'], 'phone_code' => 387],
            ['id' => 28, 'code' => 'BW', 'en' => ['name' => 'Botswana'], 'tr' => ['name' => 'Botsvana'], 'phone_code' => 267],
            ['id' => 29, 'code' => 'BV', 'en' => ['name' => 'Bouvet Island'], 'tr' => ['name' => 'Bouvet Adası'], 'phone_code' => 0],
            ['id' => 30, 'code' => 'BR', 'en' => ['name' => 'Brazil'], 'tr' => ['name' => 'Brezilya'], 'phone_code' => 55],
            ['id' => 31, 'code' => 'IO', 'en' => ['name' => 'British Indian Ocean Territory'], 'tr' => ['name' => 'Britanya Hint Okyanusu Adası'], 'phone_code' => 246],
            ['id' => 32, 'code' => 'BN', 'en' => ['name' => 'Brunei'], 'tr' => ['name' => 'Brunei'], 'phone_code' => 673],
            ['id' => 33, 'code' => 'BG', 'en' => ['name' => 'Bulgaria'], 'tr' => ['name' => 'Bulgaristan'], 'phone_code' => 359],
            ['id' => 34, 'code' => 'BF', 'en' => ['name' => 'Burkina Faso'], 'tr' => ['name' => 'Burkina Faso'], 'phone_code' => 226],
            ['id' => 35, 'code' => 'BI', 'en' => ['name' => 'Burundi'], 'tr' => ['name' => 'Burundi'], 'phone_code' => 257],
            ['id' => 36, 'code' => 'KH', 'en' => ['name' => 'Cambodia'], 'tr' => ['name' => 'Kamboçya'], 'phone_code' => 855],
            ['id' => 37, 'code' => 'CM', 'en' => ['name' => 'Cameroon'], 'tr' => ['name' => 'Kamerun'], 'phone_code' => 237],
            ['id' => 38, 'code' => 'CA', 'en' => ['name' => 'Canada'], 'tr' => ['name' => 'Kanada'], 'phone_code' => 1],
            ['id' => 39, 'code' => 'CV', 'en' => ['name' => 'Cape Verde'], 'tr' => ['name' => 'Cape Verde'], 'phone_code' => 238],
            ['id' => 40, 'code' => 'KY', 'en' => ['name' => 'Cayman Islands'], 'tr' => ['name' => 'Cayman Adaları'], 'phone_code' => 1345],
            ['id' => 41, 'code' => 'CF', 'en' => ['name' => 'Central African Republic'], 'tr' => ['name' => 'Orta Afrika Cumhuriyeti'], 'phone_code' => 236],
            ['id' => 42, 'code' => 'TD', 'en' => ['name' => 'Chad'], 'tr' => ['name' => 'Çad'], 'phone_code' => 235],
            ['id' => 43, 'code' => 'CL', 'en' => ['name' => 'Chile'], 'tr' => ['name' => 'Şili'], 'phone_code' => 56],
            ['id' => 44, 'code' => 'CN', 'en' => ['name' => 'China'], 'tr' => ['name' => 'Çin'], 'phone_code' => 86],
            ['id' => 45, 'code' => 'CX', 'en' => ['name' => 'Christmas Island'], 'tr' => ['name' => 'Christmas Adası'], 'phone_code' => 61],
            ['id' => 46, 'code' => 'CC', 'en' => ['name' => 'Cocos (Keeling) Islands'], 'tr' => ['name' => 'Cocos (Keeling) Adaları'], 'phone_code' => 672],
            ['id' => 47, 'code' => 'CO', 'en' => ['name' => 'Colombia'], 'tr' => ['name' => 'Kolombiya'], 'phone_code' => 57],
            ['id' => 48, 'code' => 'KM', 'en' => ['name' => 'Comoros'], 'tr' => ['name' => 'Komorlar'], 'phone_code' => 269],
            ['id' => 49, 'code' => 'CG', 'en' => ['name' => 'Congo'], 'tr' => ['name' => 'Kongo'], 'phone_code' => 242],
            ['id' => 50, 'code' => 'CD', 'en' => ['name' => 'Congo The Democratic Republic Of The'], 'tr' => ['name' => 'Kongo Cumhuriyeti'], 'phone_code' => 242],
            ['id' => 51, 'code' => 'CK', 'en' => ['name' => 'Cook Islands'], 'tr' => ['name' => 'Cook Adaları'], 'phone_code' => 682],
            ['id' => 52, 'code' => 'CR', 'en' => ['name' => 'Costa Rica'], 'tr' => ['name' => 'Kosta Rika'], 'phone_code' => 506],
            ['id' => 53, 'code' => 'CI', 'en' => ['name' => 'Cote D Ivoire (Ivory Coast)'], 'tr' => ['name' => "Côte D'Ivoire (Ivory Coast)"], 'phone_code' => 225],
            ['id' => 54, 'code' => 'HR', 'en' => ['name' => 'Croatia (Hrvatska)'], 'tr' => ['name' => 'Hrvatska'], 'phone_code' => 385],
            ['id' => 55, 'code' => 'CU', 'en' => ['name' => 'Cuba'], 'tr' => ['name' => 'Küba'], 'phone_code' => 53],
            ['id' => 56, 'code' => 'CY', 'en' => ['name' => 'Cyprus'], 'tr' => ['name' => 'Kıbrıs'], 'phone_code' => 357],
            ['id' => 57, 'code' => 'CZ', 'en' => ['name' => 'Czech Republic'], 'tr' => ['name' => 'Çek Cumhuriyeti'], 'phone_code' => 420],
            ['id' => 58, 'code' => 'DK', 'en' => ['name' => 'Denmark'], 'tr' => ['name' => 'Danimarka'], 'phone_code' => 45],
            ['id' => 59, 'code' => 'DJ', 'en' => ['name' => 'Djibouti'], 'tr' => ['name' => 'Djibouti'], 'phone_code' => 253],
            ['id' => 60, 'code' => 'DM', 'en' => ['name' => 'Dominica'], 'tr' => ['name' => 'Dominika'], 'phone_code' => 1767],
            ['id' => 61, 'code' => 'DO', 'en' => ['name' => 'Dominican Republic'], 'tr' => ['name' => 'Dominik Cumhuriyeti'], 'phone_code' => 1809],
            ['id' => 62, 'code' => 'TP', 'en' => ['name' => 'East Timor'], 'tr' => ['name' => 'Doğu Timor'], 'phone_code' => 670],
            ['id' => 63, 'code' => 'EC', 'en' => ['name' => 'Ecuador'], 'tr' => ['name' => 'Ekvador'], 'phone_code' => 593],
            ['id' => 64, 'code' => 'EG', 'en' => ['name' => 'Egypt'], 'tr' => ['name' => 'Mısır'], 'phone_code' => 20],
            ['id' => 65, 'code' => 'SV', 'en' => ['name' => 'El Salvador'], 'tr' => ['name' => 'El Salvador'], 'phone_code' => 503],
            ['id' => 66, 'code' => 'GQ', 'en' => ['name' => 'Equatorial Guinea'], 'tr' => ['name' => 'Ekvator Ginesi'], 'phone_code' => 240],
            ['id' => 67, 'code' => 'ER', 'en' => ['name' => 'Eritrea'], 'tr' => ['name' => 'Eritre'], 'phone_code' => 291],
            ['id' => 68, 'code' => 'EE', 'en' => ['name' => 'Estonia'], 'tr' => ['name' => 'Estonya'], 'phone_code' => 372],
            ['id' => 69, 'code' => 'ET', 'en' => ['name' => 'Ethiopia'], 'tr' => ['name' => 'Etiyopya'], 'phone_code' => 251],
            ['id' => 70, 'code' => 'XA', 'en' => ['name' => 'External Territories of Australia'], 'tr' => ['name' => 'Avrupa Dışında Avustralya'], 'phone_code' => 61],
            ['id' => 71, 'code' => 'FK', 'en' => ['name' => 'Falkland Islands'], 'tr' => ['name' => 'Falkland Adaları'], 'phone_code' => 500],
            ['id' => 72, 'code' => 'FO', 'en' => ['name' => 'Faroe Islands'], 'tr' => ['name' => 'Faroe Adaları'], 'phone_code' => 298],
            ['id' => 73, 'code' => 'FJ', 'en' => ['name' => 'Fiji Islands'], 'tr' => ['name' => 'Fiji Adaları'], 'phone_code' => 679],
            ['id' => 74, 'code' => 'FI', 'en' => ['name' => 'Finland'], 'tr' => ['name' => 'Finlandiya'], 'phone_code' => 358],
            ['id' => 75, 'code' => 'FR', 'en' => ['name' => 'France'], 'tr' => ['name' => 'Fransa'], 'phone_code' => 33],
            ['id' => 76, 'code' => 'GF', 'en' => ['name' => 'French Guiana'], 'tr' => ['name' => 'Fransız Guyanası'], 'phone_code' => 594],
            ['id' => 77, 'code' => 'PF', 'en' => ['name' => 'French Polynesia'], 'tr' => ['name' => 'Fransız Polinezyası'], 'phone_code' => 689],
            ['id' => 78, 'code' => 'TF', 'en' => ['name' => 'French Southern Territories'], 'tr' => ['name' => 'Fransız Güney Adaları'], 'phone_code' => 0],
            ['id' => 79, 'code' => 'GA', 'en' => ['name' => 'Gabon'], 'tr' => ['name' => 'Gabon'], 'phone_code' => 241],
            ['id' => 80, 'code' => 'GM', 'en' => ['name' => 'Gambia The'], 'tr' => ['name' => 'Gambiya'], 'phone_code' => 220],
            ['id' => 81, 'code' => 'GE', 'en' => ['name' => 'Georgia'], 'tr' => ['name' => 'Gürcistan'], 'phone_code' => 995],
            ['id' => 82, 'code' => 'DE', 'en' => ['name' => 'Germany'], 'tr' => ['name' => 'Almanya'], 'phone_code' => 49],
            ['id' => 83, 'code' => 'GH', 'en' => ['name' => 'Ghana'], 'tr' => ['name' => 'Gana'], 'phone_code' => 233],
            ['id' => 84, 'code' => 'GI', 'en' => ['name' => 'Gibraltar'], 'tr' => ['name' => 'Gibraltar'], 'phone_code' => 350],
            ['id' => 85, 'code' => 'GR', 'en' => ['name' => 'Greece'], 'tr' => ['name' => 'Yunanistan'], 'phone_code' => 30],
            ['id' => 86, 'code' => 'GL', 'en' => ['name' => 'Greenland'], 'tr' => ['name' => 'Grönland'], 'phone_code' => 299],
            ['id' => 87, 'code' => 'GD', 'en' => ['name' => 'Grenada'], 'tr' => ['name' => 'Grenada'], 'phone_code' => 1473],
            ['id' => 88, 'code' => 'GP', 'en' => ['name' => 'Guadeloupe'], 'tr' => ['name' => 'Guadeloupe'], 'phone_code' => 590],
            ['id' => 89, 'code' => 'GU', 'en' => ['name' => 'Guam'], 'tr' => ['name' => 'Guam'], 'phone_code' => 1671],
            ['id' => 90, 'code' => 'GT', 'en' => ['name' => 'Guatemala'], 'tr' => ['name' => 'Guatemala'], 'phone_code' => 502],
            ['id' => 91, 'code' => 'XU', 'en' => ['name' => 'Guernsey and Alderney'], 'tr' => ['name' => 'Guernsey ve Alderney'], 'phone_code' => 44],
            ['id' => 92, 'code' => 'GN', 'en' => ['name' => 'Guinea'], 'tr' => ['name' => 'Gine'], 'phone_code' => 224],
            ['id' => 93, 'code' => 'GW', 'en' => ['name' => 'Guinea-Bissau'], 'tr' => ['name' => 'Gine-Bissau'], 'phone_code' => 245],
            ['id' => 94, 'code' => 'GY', 'en' => ['name' => 'Guyana'], 'tr' => ['name' => 'Guyana'], 'phone_code' => 592],
            ['id' => 95, 'code' => 'HT', 'en' => ['name' => 'Haiti'], 'tr' => ['name' => 'Haiti'], 'phone_code' => 509],
            ['id' => 96, 'code' => 'HM', 'en' => ['name' => 'Heard and McDonald Islands'], 'tr' => ['name' => 'Heard ve McDonald Adaları'], 'phone_code' => 0],
            ['id' => 97, 'code' => 'HN', 'en' => ['name' => 'Honduras'], 'tr' => ['name' => 'Honduras'], 'phone_code' => 504],
            ['id' => 98, 'code' => 'HK', 'en' => ['name' => 'Hong Kong S.A.R.'], 'tr' => ['name' => 'Hong Kong S.A.R.'], 'phone_code' => 852],
            ['id' => 99, 'code' => 'HU', 'en' => ['name' => 'Hungary'], 'tr' => ['name' => 'Macaristan'], 'phone_code' => 36],
            ['id' => 100, 'code' => 'IS', 'en' => ['name' => 'Iceland'], 'tr' => ['name' => 'İzlanda'], 'phone_code' => 354],
            ['id' => 101, 'code' => 'IN', 'en' => ['name' => 'India'], 'tr' => ['name' => 'Hindistan'], 'phone_code' => 91],
            ['id' => 102, 'code' => 'ID', 'en' => ['name' => 'Indonesia'], 'tr' => ['name' => 'Endonezya'], 'phone_code' => 62],
            ['id' => 103, 'code' => 'IR', 'en' => ['name' => 'Iran'], 'tr' => ['name' => 'İran'], 'phone_code' => 98],
            ['id' => 104, 'code' => 'IQ', 'en' => ['name' => 'Iraq'], 'tr' => ['name' => 'Irak'], 'phone_code' => 964],
            ['id' => 105, 'code' => 'IE', 'en' => ['name' => 'Ireland'], 'tr' => ['name' => 'İrlandiya'], 'phone_code' => 353],
            ['id' => 106, 'code' => 'IL', 'en' => ['name' => 'Israel'], 'tr' => ['name' => 'İsrail'], 'phone_code' => 972],
            ['id' => 107, 'code' => 'IT', 'en' => ['name' => 'Italy'], 'tr' => ['name' => 'İtalya'], 'phone_code' => 39],
            ['id' => 108, 'code' => 'JM', 'en' => ['name' => 'Jamaica'], 'tr' => ['name' => 'Jamaika'], 'phone_code' => 1876],
            ['id' => 109, 'code' => 'JP', 'en' => ['name' => 'Japan'], 'tr' => ['name' => 'Japonya'], 'phone_code' => 81],
            ['id' => 110, 'code' => 'XJ', 'en' => ['name' => 'Jersey'], 'tr' => ['name' => 'Jersey'], 'phone_code' => 44],
            ['id' => 111, 'code' => 'JO', 'en' => ['name' => 'Jordan'], 'tr' => ['name' => 'Ürdün'], 'phone_code' => 962],
            ['id' => 112, 'code' => 'KZ', 'en' => ['name' => 'Kazakhstan'], 'tr' => ['name' => 'Kazakistan'], 'phone_code' => 7],
            ['id' => 113, 'code' => 'KE', 'en' => ['name' => 'Kenya'], 'tr' => ['name' => 'Kenya'], 'phone_code' => 254],
            ['id' => 114, 'code' => 'KI', 'en' => ['name' => 'Kiribati'], 'tr' => ['name' => 'Kiribati'], 'phone_code' => 686],
            ['id' => 115, 'code' => 'KP', 'en' => ['name' => 'Korea North'], 'tr' => ['name' => 'Kore Cumhuriyeti'], 'phone_code' => 850],
            ['id' => 116, 'code' => 'KR', 'en' => ['name' => 'Korea South'], 'tr' => ['name' => 'Güney Kore'], 'phone_code' => 82],
            ['id' => 117, 'code' => 'KW', 'en' => ['name' => 'Kuwait'], 'tr' => ['name' => 'Kuveyt'], 'phone_code' => 965],
            ['id' => 118, 'code' => 'KG', 'en' => ['name' => 'Kyrgyzstan'], 'tr' => ['name' => 'Kırgızistan'], 'phone_code' => 996],
            ['id' => 119, 'code' => 'LA', 'en' => ['name' => 'Laos'], 'tr' => ['name' => 'Laos'], 'phone_code' => 856],
            ['id' => 120, 'code' => 'LV', 'en' => ['name' => 'Latvia'], 'tr' => ['name' => 'Litvanya'], 'phone_code' => 371],
            ['id' => 121, 'code' => 'LB', 'en' => ['name' => 'Lebanon'], 'tr' => ['name' => 'Lübnan'], 'phone_code' => 961],
            ['id' => 122, 'code' => 'LS', 'en' => ['name' => 'Lesotho'], 'tr' => ['name' => 'Lesotho'], 'phone_code' => 266],
            ['id' => 123, 'code' => 'LR', 'en' => ['name' => 'Liberia'], 'tr' => ['name' => 'Liberya'], 'phone_code' => 231],
            ['id' => 124, 'code' => 'LY', 'en' => ['name' => 'Libya'], 'tr' => ['name' => 'Libya'], 'phone_code' => 218],
            ['id' => 125, 'code' => 'LI', 'en' => ['name' => 'Liechtenstein'], 'tr' => ['name' => 'Lihtenştayn'], 'phone_code' => 423],
            ['id' => 126, 'code' => 'LT', 'en' => ['name' => 'Lithuania'], 'tr' => ['name' => 'Litvanya'], 'phone_code' => 370],
            ['id' => 127, 'code' => 'LU', 'en' => ['name' => 'Luxembourg'], 'tr' => ['name' => 'Lüksemburg'], 'phone_code' => 352],
            ['id' => 128, 'code' => 'MO', 'en' => ['name' => 'Macau S.A.R.'], 'tr' => ['name' => 'Makau S.A.R.'], 'phone_code' => 853],
            ['id' => 129, 'code' => 'MK', 'en' => ['name' => 'Macedonia'], 'tr' => ['name' => 'Makedonya'], 'phone_code' => 389],
            ['id' => 130, 'code' => 'MG', 'en' => ['name' => 'Madagascar'], 'tr' => ['name' => 'Madagaskar'], 'phone_code' => 261],
            ['id' => 131, 'code' => 'MW', 'en' => ['name' => 'Malawi'], 'tr' => ['name' => 'Malawi'], 'phone_code' => 265],
            ['id' => 132, 'code' => 'MY', 'en' => ['name' => 'Malaysia'], 'tr' => ['name' => 'Malaysia'], 'phone_code' => 60],
            ['id' => 133, 'code' => 'MV', 'en' => ['name' => 'Maldives'], 'tr' => ['name' => 'Maldivler'], 'phone_code' => 960],
            ['id' => 134, 'code' => 'ML', 'en' => ['name' => 'Mali'], 'tr' => ['name' => 'Mali'], 'phone_code' => 223],
            ['id' => 135, 'code' => 'MT', 'en' => ['name' => 'Malta'], 'tr' => ['name' => 'Malta'], 'phone_code' => 356],
            ['id' => 136, 'code' => 'XM', 'en' => ['name' => 'Man (Isle of)'], 'tr' => ['name' => 'Man Adası'], 'phone_code' => 44],
            ['id' => 137, 'code' => 'MH', 'en' => ['name' => 'Marshall Islands'], 'tr' => ['name' => 'Marshall Adaları'], 'phone_code' => 692],
            ['id' => 138, 'code' => 'MQ', 'en' => ['name' => 'Martinique'], 'tr' => ['name' => 'Martinik'], 'phone_code' => 596],
            ['id' => 139, 'code' => 'MR', 'en' => ['name' => 'Mauritania'], 'tr' => ['name' => 'Mauritania'], 'phone_code' => 222],
            ['id' => 140, 'code' => 'MU', 'en' => ['name' => 'Mauritius'], 'tr' => ['name' => 'Mauritius'], 'phone_code' => 230],
            ['id' => 141, 'code' => 'YT', 'en' => ['name' => 'Mayotte'], 'tr' => ['name' => 'Mayotte'], 'phone_code' => 269],
            ['id' => 142, 'code' => 'MX', 'en' => ['name' => 'Mexico'], 'tr' => ['name' => 'Meksika'], 'phone_code' => 52],
            ['id' => 143, 'code' => 'FM', 'en' => ['name' => 'Micronesia'], 'tr' => ['name' => 'Mikronezya'], 'phone_code' => 691],
            ['id' => 144, 'code' => 'MD', 'en' => ['name' => 'Moldova'], 'tr' => ['name' => 'Moldova'], 'phone_code' => 373],
            ['id' => 145, 'code' => 'MC', 'en' => ['name' => 'Monaco'], 'tr' => ['name' => 'Monako'], 'phone_code' => 377],
            ['id' => 146, 'code' => 'MN', 'en' => ['name' => 'Mongolia'], 'tr' => ['name' => 'Mongolia'], 'phone_code' => 976],
            ['id' => 147, 'code' => 'MS', 'en' => ['name' => 'Montserrat'], 'tr' => ['name' => 'Montserrat'], 'phone_code' => 1664],
            ['id' => 148, 'code' => 'MA', 'en' => ['name' => 'Morocco'], 'tr' => ['name' => 'Fas'], 'phone_code' => 212],
            ['id' => 149, 'code' => 'MZ', 'en' => ['name' => 'Mozambique'], 'tr' => ['name' => 'Mozambik'], 'phone_code' => 258],
            ['id' => 150, 'code' => 'MM', 'en' => ['name' => 'Myanmar'], 'tr' => ['name' => 'Myanmar'], 'phone_code' => 95],
            ['id' => 151, 'code' => 'NA', 'en' => ['name' => 'Namibia'], 'tr' => ['name' => 'Namibia'], 'phone_code' => 264],
            ['id' => 152, 'code' => 'NR', 'en' => ['name' => 'Nauru'], 'tr' => ['name' => 'Nauru'], 'phone_code' => 674],
            ['id' => 153, 'code' => 'NP', 'en' => ['name' => 'Nepal'], 'tr' => ['name' => 'Nepal'], 'phone_code' => 977],
            ['id' => 154, 'code' => 'AN', 'en' => ['name' => 'Netherlands Antilles'], 'tr' => ['name' => 'Hollanda Antillerleri'], 'phone_code' => 599],
            ['id' => 155, 'code' => 'NL', 'en' => ['name' => 'Netherlands The'], 'tr' => ['name' => 'Hollanda'], 'phone_code' => 31],
            ['id' => 156, 'code' => 'NC', 'en' => ['name' => 'New Caledonia'], 'tr' => ['name' => 'Yeni Kaledonya'], 'phone_code' => 687],
            ['id' => 157, 'code' => 'NZ', 'en' => ['name' => 'New Zealand'], 'tr' => ['name' => 'Yeni Zelanda'], 'phone_code' => 64],
            ['id' => 158, 'code' => 'NI', 'en' => ['name' => 'Nicaragua'], 'tr' => ['name' => 'Nikaragua'], 'phone_code' => 505],
            ['id' => 159, 'code' => 'NE', 'en' => ['name' => 'Niger'], 'tr' => ['name' => 'Niger'], 'phone_code' => 227],
            ['id' => 160, 'code' => 'NG', 'en' => ['name' => 'Nigeria'], 'tr' => ['name' => 'Nigeriya'], 'phone_code' => 234],
            ['id' => 161, 'code' => 'NU', 'en' => ['name' => 'Niue'], 'tr' => ['name' => 'Niue'], 'phone_code' => 683],
            ['id' => 162, 'code' => 'NF', 'en' => ['name' => 'Norfolk Island'], 'tr' => ['name' => 'Norfolk Adası'], 'phone_code' => 672],
            ['id' => 163, 'code' => 'MP', 'en' => ['name' => 'Northern Mariana Islands'], 'tr' => ['name' => 'Kuzey Marian Adaları'], 'phone_code' => 1670],
            ['id' => 164, 'code' => 'NO', 'en' => ['name' => 'Norway'], 'tr' => ['name' => 'Norveç'], 'phone_code' => 47],
            ['id' => 165, 'code' => 'OM', 'en' => ['name' => 'Oman'], 'tr' => ['name' => 'Oman'], 'phone_code' => 968],
            ['id' => 166, 'code' => 'PK', 'en' => ['name' => 'Pakistan'], 'tr' => ['name' => 'Pakistan'], 'phone_code' => 92],
            ['id' => 167, 'code' => 'PW', 'en' => ['name' => 'Palau'], 'tr' => ['name' => 'Palau'], 'phone_code' => 680],
            ['id' => 168, 'code' => 'PS', 'en' => ['name' => 'Palestinian Territory Occupied'], 'tr' => ['name' => 'Fetih Bölgeleri'], 'phone_code' => 970],
            ['id' => 169, 'code' => 'PA', 'en' => ['name' => 'Panama'], 'tr' => ['name' => 'Panama'], 'phone_code' => 507],
            ['id' => 170, 'code' => 'PG', 'en' => ['name' => 'Papua new Guinea'], 'tr' => ['name' => 'Papua Yeni Gine'], 'phone_code' => 675],
            ['id' => 171, 'code' => 'PY', 'en' => ['name' => 'Paraguay'], 'tr' => ['name' => 'Paraguay'], 'phone_code' => 595],
            ['id' => 172, 'code' => 'PE', 'en' => ['name' => 'Peru'], 'tr' => ['name' => 'Peru'], 'phone_code' => 51],
            ['id' => 173, 'code' => 'PH', 'en' => ['name' => 'Philippines'], 'tr' => ['name' => 'Filipinler'], 'phone_code' => 63],
            ['id' => 174, 'code' => 'PN', 'en' => ['name' => 'Pitcairn Island'], 'tr' => ['name' => 'Pitcairn Adası'], 'phone_code' => 0],
            ['id' => 175, 'code' => 'PL', 'en' => ['name' => 'Poland'], 'tr' => ['name' => 'Polonya'], 'phone_code' => 48],
            ['id' => 176, 'code' => 'PT', 'en' => ['name' => 'Portugal'], 'tr' => ['name' => 'Portekiz'], 'phone_code' => 351],
            ['id' => 177, 'code' => 'PR', 'en' => ['name' => 'Puerto Rico'], 'tr' => ['name' => 'Porto Riko'], 'phone_code' => 1787],
            ['id' => 178, 'code' => 'QA', 'en' => ['name' => 'Qatar'], 'tr' => ['name' => 'Katar'], 'phone_code' => 974],
            ['id' => 179, 'code' => 'RE', 'en' => ['name' => 'Reunion'], 'tr' => ['name' => 'Reunion'], 'phone_code' => 262],
            ['id' => 180, 'code' => 'RO', 'en' => ['name' => 'Romania'], 'tr' => ['name' => 'Romanya'], 'phone_code' => 40],
            ['id' => 181, 'code' => 'RU', 'en' => ['name' => 'Russia'], 'tr' => ['name' => 'Rusya'], 'phone_code' => 70],
            ['id' => 182, 'code' => 'RW', 'en' => ['name' => 'Rwanda'], 'tr' => ['name' => 'Rwanda'], 'phone_code' => 250],
            ['id' => 183, 'code' => 'SH', 'en' => ['name' => 'Saint Helena'], 'tr' => ['name' => 'Saint Helena'], 'phone_code' => 290],
            ['id' => 184, 'code' => 'KN', 'en' => ['name' => 'Saint Kitts And Nevis'], 'tr' => ['name' => 'Saint Kitts And Nevis'], 'phone_code' => 1869],
            ['id' => 185, 'code' => 'LC', 'en' => ['name' => 'Saint Lucia'], 'tr' => ['name' => 'Saint Lucia'], 'phone_code' => 1758],
            ['id' => 186, 'code' => 'PM', 'en' => ['name' => 'Saint Pierre and Miquelon'], 'tr' => ['name' => 'Saint Pierre and Miquelon'], 'phone_code' => 508],
            ['id' => 187, 'code' => 'VC', 'en' => ['name' => 'Saint Vincent And The Grenadines'], 'tr' => ['name' => 'Saint Vincent And The Grenadines'], 'phone_code' => 1784],
            ['id' => 188, 'code' => 'WS', 'en' => ['name' => 'Samoa'], 'tr' => ['name' => 'Samoa'], 'phone_code' => 684],
            ['id' => 189, 'code' => 'SM', 'en' => ['name' => 'San Marino'], 'tr' => ['name' => 'San Marino'], 'phone_code' => 378],
            ['id' => 190, 'code' => 'ST', 'en' => ['name' => 'Sao Tome and Principe'], 'tr' => ['name' => 'Sao Tome and Principe'], 'phone_code' => 239],
            ['id' => 191, 'code' => 'SA', 'en' => ['name' => 'Saudi Arabia'], 'tr' => ['name' => 'Suudi Arabistan'], 'phone_code' => 966],
            ['id' => 192, 'code' => 'SN', 'en' => ['name' => 'Senegal'], 'tr' => ['name' => 'Senegal'], 'phone_code' => 221],
            ['id' => 193, 'code' => 'RS', 'en' => ['name' => 'Serbia'], 'tr' => ['name' => 'Sırbistan'], 'phone_code' => 381],
            ['id' => 194, 'code' => 'SC', 'en' => ['name' => 'Seychelles'], 'tr' => ['name' => 'Seyşeller'], 'phone_code' => 248],
            ['id' => 195, 'code' => 'SL', 'en' => ['name' => 'Sierra Leone'], 'tr' => ['name' => 'Sierra Leone'], 'phone_code' => 232],
            ['id' => 196, 'code' => 'SG', 'en' => ['name' => 'Singapore'], 'tr' => ['name' => 'Singapore'], 'phone_code' => 65],
            ['id' => 197, 'code' => 'SK', 'en' => ['name' => 'Slovakia'], 'tr' => ['name' => 'Slovakya'], 'phone_code' => 421],
            ['id' => 198, 'code' => 'SI', 'en' => ['name' => 'Slovenia'], 'tr' => ['name' => 'Slovenya'], 'phone_code' => 386],
            ['id' => 199, 'code' => 'XG', 'en' => ['name' => 'Smaller Territories of the UK'], 'tr' => ['name' => 'Küçük İngiliz Kıta'], 'phone_code' => 44],
            ['id' => 200, 'code' => 'SB', 'en' => ['name' => 'Solomon Islands'], 'tr' => ['name' => 'Solomon Adaları'], 'phone_code' => 677],
            ['id' => 201, 'code' => 'SO', 'en' => ['name' => 'Somalia'], 'tr' => ['name' => 'Somaliya'], 'phone_code' => 252],
            ['id' => 202, 'code' => 'ZA', 'en' => ['name' => 'South Africa'], 'tr' => ['name' => 'Güney Afrika'], 'phone_code' => 27],
            ['id' => 203, 'code' => 'GS', 'en' => ['name' => 'South Georgia'], 'tr' => ['name' => 'Güney Georgia'], 'phone_code' => 0],
            ['id' => 204, 'code' => 'SS', 'en' => ['name' => 'South Sudan'], 'tr' => ['name' => 'Güney Sudan'], 'phone_code' => 211],
            ['id' => 205, 'code' => 'ES', 'en' => ['name' => 'Spain'], 'tr' => ['name' => 'İspanya'], 'phone_code' => 34],
            ['id' => 206, 'code' => 'LK', 'en' => ['name' => 'Sri Lanka'], 'tr' => ['name' => 'Sri Lanka'], 'phone_code' => 94],
            ['id' => 207, 'code' => 'SD', 'en' => ['name' => 'Sudan'], 'tr' => ['name' => 'Sudan'], 'phone_code' => 249],
            ['id' => 208, 'code' => 'SR', 'en' => ['name' => 'Suriname'], 'tr' => ['name' => 'Suriname'], 'phone_code' => 597],
            ['id' => 209, 'code' => 'SJ', 'en' => ['name' => 'Svalbard And Jan Mayen Islands'], 'tr' => ['name' => 'Svalbard And Jan Mayen Islands'], 'phone_code' => 47],
            ['id' => 210, 'code' => 'SZ', 'en' => ['name' => 'Swaziland'], 'tr' => ['name' => 'Swaziland'], 'phone_code' => 268],
            ['id' => 211, 'code' => 'SE', 'en' => ['name' => 'Sweden'], 'tr' => ['name' => 'İsveç'], 'phone_code' => 46],
            ['id' => 212, 'code' => 'CH', 'en' => ['name' => 'Switzerland'], 'tr' => ['name' => 'İsviçre'], 'phone_code' => 41],
            ['id' => 213, 'code' => 'SY', 'en' => ['name' => 'Syria'], 'tr' => ['name' => 'Suriya'], 'phone_code' => 963],
            ['id' => 214, 'code' => 'TW', 'en' => ['name' => 'Taiwan'], 'tr' => ['name' => 'Tayvan'], 'phone_code' => 886],
            ['id' => 215, 'code' => 'TJ', 'en' => ['name' => 'Tajikistan'], 'tr' => ['name' => 'Tacikistan'], 'phone_code' => 992],
            ['id' => 216, 'code' => 'TZ', 'en' => ['name' => 'Tanzania'], 'tr' => ['name' => 'Tanzanya'], 'phone_code' => 255],
            ['id' => 217, 'code' => 'TH', 'en' => ['name' => 'Thailand'], 'tr' => ['name' => 'Tayland'], 'phone_code' => 66],
            ['id' => 218, 'code' => 'TG', 'en' => ['name' => 'Togo'], 'tr' => ['name' => 'Togo'], 'phone_code' => 228],
            ['id' => 219, 'code' => 'TK', 'en' => ['name' => 'Tokelau'], 'tr' => ['name' => 'Tokelau'], 'phone_code' => 690],
            ['id' => 220, 'code' => 'TO', 'en' => ['name' => 'Tonga'], 'tr' => ['name' => 'Tonga'], 'phone_code' => 676],
            ['id' => 221, 'code' => 'TT', 'en' => ['name' => 'Trinidad And Tobago'], 'tr' => ['name' => 'Trinidad And Tobago'], 'phone_code' => 1868],
            ['id' => 222, 'code' => 'TN', 'en' => ['name' => 'Tunisia'], 'tr' => ['name' => 'Tunus'], 'phone_code' => 216],
            ['id' => 223, 'code' => 'TR', 'en' => ['name' => 'Turkey'], 'tr' => ['name' => 'Türkiye'], 'phone_code' => 90],
            ['id' => 224, 'code' => 'TM', 'en' => ['name' => 'Turkmenistan'], 'tr' => ['name' => 'Türkmenistan'], 'phone_code' => 7370],
            ['id' => 225, 'code' => 'TC', 'en' => ['name' => 'Turks And Caicos Islands'], 'tr' => ['name' => 'Turks And Caicos Islands'], 'phone_code' => 1649],
            ['id' => 226, 'code' => 'TV', 'en' => ['name' => 'Tuvalu'], 'tr' => ['name' => 'Tuvalu'], 'phone_code' => 688],
            ['id' => 227, 'code' => 'UG', 'en' => ['name' => 'Uganda'], 'tr' => ['name' => 'Uganda'], 'phone_code' => 256],
            ['id' => 228, 'code' => 'UA', 'en' => ['name' => 'Ukraine'], 'tr' => ['name' => 'Ukrayna'], 'phone_code' => 380],
            ['id' => 229, 'code' => 'AE', 'en' => ['name' => 'United Arab Emirates'], 'tr' => ['name' => 'Birleşmiş Arap Emirlikleri'], 'phone_code' => 971],
            ['id' => 230, 'code' => 'GB', 'en' => ['name' => 'United Kingdom'], 'tr' => ['name' => 'Birleşik Krallık'], 'phone_code' => 44],
            ['id' => 231, 'code' => 'US', 'en' => ['name' => 'United States'], 'tr' => ['name' => 'Amerika Birleşik Devletleri'], 'phone_code' => 1],
            ['id' => 232, 'code' => 'UM', 'en' => ['name' => 'United States Minor Outlying Islands'], 'tr' => ['name' => 'Amerika Birleşik Devletleri Küçük Dış Adaları'], 'phone_code' => 1],
            ['id' => 233, 'code' => 'UY', 'en' => ['name' => 'Uruguay'], 'tr' => ['name' => 'Uruguay'], 'phone_code' => 598],
            ['id' => 234, 'code' => 'UZ', 'en' => ['name' => 'Uzbekistan'], 'tr' => ['name' => 'Özbekistan'], 'phone_code' => 998],
            ['id' => 235, 'code' => 'VU', 'en' => ['name' => 'Vanuatu'], 'tr' => ['name' => 'Vanuatu'], 'phone_code' => 678],
            ['id' => 236, 'code' => 'VA', 'en' => ['name' => 'Vatican City State (Holy See)'], 'tr' => ['name' => 'Vatikan Şehri (Kutsal Gözetim)'], 'phone_code' => 39],
            ['id' => 237, 'code' => 'VE', 'en' => ['name' => 'Venezuela'], 'tr' => ['name' => 'Venezuela'], 'phone_code' => 58],
            ['id' => 238, 'code' => 'VN', 'en' => ['name' => 'Vietnam'], 'tr' => ['name' => 'Vietnam'], 'phone_code' => 84],
            ['id' => 239, 'code' => 'VG', 'en' => ['name' => 'Virgin Islands (British)'], 'tr' => ['name' => 'Virgin Islands (British)'], 'phone_code' => 1284],
            ['id' => 240, 'code' => 'VI', 'en' => ['name' => 'Virgin Islands (US)'], 'tr' => ['name' => 'Virgin Islands (US)'], 'phone_code' => 1340],
            ['id' => 241, 'code' => 'WF', 'en' => ['name' => 'Wallis And Futuna Islands'], 'tr' => ['name' => 'Wallis And Futuna Islands'], 'phone_code' => 681],
            ['id' => 242, 'code' => 'EH', 'en' => ['name' => 'Western Sahara'], 'tr' => ['name' => 'Western Sahara'], 'phone_code' => 212],
            ['id' => 243, 'code' => 'YE', 'en' => ['name' => 'Yemen'], 'tr' => ['name' => 'Yemen'], 'phone_code' => 967],
            ['id' => 244, 'code' => 'YU', 'en' => ['name' => 'Yugoslavia'], 'tr' => ['name' => 'Yugoslavia'], 'phone_code' => 38],
            ['id' => 245, 'code' => 'ZM', 'en' => ['name' => 'Zambia'], 'tr' => ['name' => 'Zambia'], 'phone_code' => 260],
            ['id' => 246, 'code' => 'ZW', 'en' => ['name' => 'Zimbabwe'], 'tr' => ['name' => 'Zimbabwe'], 'phone_code' => 263],
        ];

        foreach ($countries as $country) {
            Country::create($country);
        }
    }
}
