<?php

/*
|--------------------------------------------------------------------------
| Composer File Template
|--------------------------------------------------------------------------
|
| Here is the config for the composer.json file, generated by this package
|
*/
return [
    'vendor' => 'unusualify',
    'author' => [
        'name' => 'Unusual Enterprise',
        'email' => 'software-dev@unusualgrowth.com',
    ],
    'composer-output' => false,
];
