<?php

return [
    'users' => 'admin_users',
    'companies' => 'umod_companies',
    'fileponds' => 'umod_fileponds',
    'filepond_temporaries' => 'umod_filepond_temporaries',
    'files' => 'umod_files',
    'fileables' => 'umod_fileables',
    'medias' => 'umod_medias',
    'mediables' => 'umod_mediables',
    'tagged' => 'umod_tagged',
    'tags' => 'umod_tags',
    'repeaters' => 'umod_repeaters',
    'authorizeds' => 'umod_authorizeds',
    'creator_records' => 'umod_creator_records',
    'payments' => 'umod_payments',
    'states' => 'umod_states',
    'state_translations' => 'umod_state_translations',
    'stateables' => 'umod_stateables',
    'chats' => 'umod_chats',
    'chat_messages' => 'umod_chat_messages',
    'spreads' => 'umod_spreads',
    'singletons' => 'umod_singletons',
    'authorizations' => 'umod_authorizations',
    'processes' => 'umod_processes',
    'process_histories' => 'umod_process_histories',
    'assignments' => 'um_assignments',
    'user_oauths' => 'um_user_oauths',
];
