<?php

return [
    'users' => 'um_users',
    'companies' => 'um_companies',
    'fileponds' => 'um_fileponds',
    'filepond_temporaries' => 'um_filepond_temporaries',
    'files' => 'um_files',
    'fileables' => 'um_fileables',
    'medias' => 'um_medias',
    'mediables' => 'um_mediables',
    'tagged' => 'um_tagged',
    'tags' => 'um_tags',
    'repeaters' => 'um_repeaters',
    'authorizeds' => 'um_authorizeds',
    'creator_records' => 'um_creator_records',
    'payments' => 'um_payments',
    'states' => 'um_states',
    'state_translations' => 'um_state_translations',
    'stateables' => 'um_stateables',
    'chats' => 'um_chats',
    'chat_messages' => 'um_chat_messages',
    'spreads' => 'um_spreads',
    'singletons' => 'um_singletons',
    'authorizations' => 'um_authorizations',
    'processes' => 'um_processes',
    'process_histories' => 'um_process_histories',
    'assignments' => 'um_assignments',
    'user_oauths' => 'um_user_oauths',
    'email_verification_tokens' => 'um_email_verification_tokens',
    'countries' => 'um_countries',
    'country_translations' => 'um_country_translations',
    'demands' => 'um_demands',
];
