<?php

return [
    'users' => 'um_users',
    'companies' => 'um_companies',
    'fileponds' => 'um_fileponds',
    'filepond_temporaries' => 'um_filepond_temporaries',
    'files' => 'um_files',
    'fileables' => 'um_fileables',
    'medias' => 'um_medias',
    'mediables' => 'um_mediables',
    'tagged' => 'um_tagged',
    'tags' => 'um_tags',
    'repeaters' => 'um_repeaters',
    'authorizeds' => 'um_authorizeds',
    'creator_records' => 'um_creator_records',
    'payments' => 'um_payments',
    'states' => 'um_states',
    'state_translations' => 'um_state_translations',
    'stateables' => 'um_stateables',
    'chats' => 'um_chats',
    'chat_messages' => 'um_chat_messages',
    'spreads' => 'um_spreads',
    'remote_api_sources' => 'um_remote_api_sources',
    'singletons' => 'um_singletons',
    'authorizations' => 'um_authorizations',
    'processes' => 'um_processes',
    'process_histories' => 'um_process_histories',
    'assignments' => 'um_assignments',
    'user_oauths' => 'um_user_oauths',
    'capabilities' => 'um_capabilities',
    'capability_routes' => 'um_capability_routes',
    'role_capability' => 'um_role_capability',
    'capability_capability_route' => 'um_capability_capability_route',
    'email_verification_tokens' => 'um_email_verification_tokens',
    'countries' => 'um_countries',
    'country_translations' => 'um_country_translations',

    'cms_pages' => 'um_cms_pages',
    'cms_page_translations' => 'um_cms_page_translations',
    'cms_pages_revisions' => 'um_cms_pages_revisions',
    'cms_redirects' => 'um_cms_redirects',
    'cms_site_settings' => 'um_cms_site_settings',
    'cms_search_indexes' => 'um_cms_search_indexes',
    'cms_page_slugs' => 'um_cms_page_slugs',
    'cms_url_routes' => 'um_cms_url_routes',
    'cms_parent_segment_bindings' => 'um_cms_parent_segment_bindings',
    'cms_sitemaps' => 'um_cms_sitemaps',
    'cms_sitemapables' => 'um_cms_sitemapables',
    'cms_style_sheets' => 'um_cms_style_sheets',
    'cms_layout_builders' => 'um_cms_layout_builders',
    'cms_page_layouts' => 'um_cms_page_layouts',
    'cms_error_pages' => 'um_cms_error_pages',
];
