# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

on:
  push:
    branches:
      - 12.x-dev
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '**.yaml'
  pull_request:
    branches:
      - 12.x-dev
      - 12.x
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '**.yaml'
jobs:
  vue_changes:
    name: Check Vue changes
    runs-on: ubuntu-latest
    outputs:
      is_changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            vue/**/*.vue
            vue/src/**

  vue:
    needs: vue_changes
    name: Vue Tests
    runs-on: ubuntu-latest
    if: ${{ needs.vue_changes.outputs.is_changed == 'true' }}
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "vue/package-lock.json"

      #- run: npm run build --if-present
      - name: Execute Tests
        working-directory: 'vue'
        run: |
          npm ci
          npm run test:run
  laravel_changes:
    name: Check Laravel changes
    runs-on: ubuntu-latest
    outputs:
      is_changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            src/**
            modules/**
            vue/src/**
            tests/**
            routes/**
            resources/**
            database/**
            config/**
  laravel:
    needs: laravel_changes
    runs-on: ubuntu-latest
    if: ${{ needs.laravel_changes.outputs.is_changed == 'true' }}
    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3, 8.4, 8.5]
        laravel: [12.x]
        dependency_version: [prefer-stable]
        include:
          - laravel: 12.x
            testbench: ^10.0

    # This name will now resolve correctly for every combination
    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - ${{ matrix.dependency_version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Install dependencies
        run: |
            # composer config platform.php ${{ matrix.php }}
            composer install --ignore-platform-reqs
            composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
            # composer update --prefer-dist --no-interaction
      - name: Execute Laravel tests
        run: composer test

