name: Workflow test

on:
  push:
    branches:
      - 'debug/**'

permissions:
  contents: write

jobs:

  debug:
    name: Debug
    # needs: laravel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: Install Pint
        run: composer global require laravel/pint

      - name: Run Pint
        run: pint

      - name: Commit linted files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style(laravel): lint coding styles"
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: See last commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git log -1
