name: Issue to Project

on:
  issues:
    types: [opened, labeled]

permissions:
  issues: read
  repository-projects: write

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Automated Issue Carrier
        uses: oobook/automated-issue-carrier@v1.0.2
        id: automated-issue-carrier
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          projects: "*"
          labels: "bug,accepted enhancement,accepted"
          item_fields: "Status:Backlog,Size:S,Priority:P2"
          test: "true"
