name: Issue to Project

on:
  issues:
    types: [opened, labeled]

permissions:
  issues: read
  repository-projects: write

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: oobook/automated-issue-carrier@v1
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          projects: "Modularity v0"
          labels: "bug,accepted enhancement,accepted"
          item_fields: "Status:Backlog,Size:S,Priority:P2"
          test: true